/*! Jack Perfumaria — layout personalizado | Agência Raliss · Sites com a Lari */
(function(){var run=function(){(async()=>{
if(window.__JKB)return;window.__JKB=1;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=t=>String(t).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const S=(p,w=1.3,cls='jk-ico')=>`<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${w}" stroke-linecap="round" stroke-linejoin="round">${p}</svg>`;
const I={search:'<circle cx="10.5" cy="10.5" r="6"/><path d="M15 15l5.2 5.2"/><path d="M8 8.6c.6-.9 1.6-1.4 2.6-1.4"/>',user:'<circle cx="12" cy="8.2" r="3.6"/><path d="M5 20.2c1.1-3.6 3.9-5.6 7-5.6s5.9 2 7 5.6"/>',bag:'<path d="M5.6 8.8h12.8l-.9 11.4H6.5z"/><path d="M9.2 8.8V7.1a2.8 2.8 0 0 1 5.6 0v1.7"/><path d="M10.4 13.4c.5.7 1 1 1.6 1s1.1-.3 1.6-1"/>',bars:'<path d="M4 7.5h16M4 12h10M4 16.5h16"/>',x:'<path d="M5 5l14 14M19 5L5 19"/>',plus:'<path d="M12 5v14M5 12h14"/>',back:'<path d="M19 12H5M11 6l-6 6 6 6"/>',ig:'<rect x="3.5" y="3.5" width="17" height="17" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.2" cy="6.8" r=".6" fill="currentColor"/>',arrow:'<path d="M4 12h16M14.5 6.5L20 12l-5.5 5.5"/>',wa:'<path d="M3.6 20.4l1.3-4.1A8.6 8.6 0 1 1 8 19.3z" stroke-width="1.25"/><path d="M9 8.3c.2-.4.5-.5.8-.5h.4c.2 0 .4.1.5.4l.7 1.6c.1.2 0 .5-.1.7l-.6.7c.7 1.4 1.8 2.5 3.2 3.2l.7-.6c.2-.2.5-.2.7-.1l1.6.7c.3.1.4.3.4.5v.4c0 .3-.1.6-.5.8-.9.6-2.1.6-3.3.1a9 9 0 0 1-4.6-4.6c-.5-1.2-.5-2.4.1-3.3z" stroke-width="1.1"/>',tel:'<path d="M7.2 3.5h2.4l1.3 4-1.8 1.3a10 10 0 0 0 6.1 6.1l1.3-1.8 4 1.3v2.4a2 2 0 0 1-2.2 2C10.6 18.4 5.6 13.4 5.2 5.7a2 2 0 0 1 2-2.2z"/>',mail:'<rect x="3.5" y="5.5" width="17" height="13" rx="1.5"/><path d="M4 6.5l8 6.5 8-6.5"/>',pin:'<path d="M12 21s-6.5-6.1-6.5-11a6.5 6.5 0 0 1 13 0c0 4.9-6.5 11-6.5 11z"/><circle cx="12" cy="10" r="2.3"/>',lock:'<rect x="5" y="10.5" width="14" height="9.5" rx="1.5"/><path d="M8 10.5V8a4 4 0 0 1 8 0v2.5"/>'};
const chevron=d=>`<svg class="jk-ar" viewBox="0 0 9 16" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">${d==='next'?'<path d="M1 1l7 7-7 7"/>':'<path d="M8 1L1 8l7 7"/>'}</svg>`;
const addArrows=sel=>$$(sel).forEach(b=>{if(!b.querySelector('.jk-ar'))b.insertAdjacentHTML('beforeend',chevron(/next/.test(b.className)?'next':'prev'))});
const pad=n=>String(n).padStart(2,'0');
if(!$('#jk-fonts')){const l=document.createElement('link');l.id='jk-fonts';l.rel='stylesheet';l.href='https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600;700&family=Pinyon+Script&display=swap';document.head.appendChild(l)}
for(const id of ['user','bag','bars']){const s=document.getElementById(id);if(s&&s.tagName.toLowerCase()==='symbol'){s.setAttribute('viewBox','0 0 24 24');s.innerHTML=`<g fill="none" stroke="currentColor" stroke-width="1.15" stroke-linecap="round" stroke-linejoin="round">${I[id]}</g>`}}
const wrapLogo=img=>{if(!img||img.parentElement.classList.contains('jk-logo-wrap'))return;const w=document.createElement('span');w.className='jk-logo-wrap';img.parentNode.insertBefore(w,img);w.appendChild(img);const set=()=>w.style.setProperty('--jk-logo',`url("${img.currentSrc||img.src}")`);set();img.addEventListener('load',set)};
const logo=$('.js-head-row .js-logo-container img');wrapLogo(logo);
const form=$('.js-head-row .js-search-form');
if(form){if(!form.querySelector('.jk-s-tag')){const t=document.createElement('span');t.className='jk-s-tag';t.textContent='Buscar';form.prepend(t)}
 const btn=form.querySelector('.js-search-input-submit');if(btn)btn.innerHTML=S(I.search,1.4);
 const inp=form.querySelector('.js-search-input');
 const cats=$$('.nav-desktop .js-desktop-nav-item').map(li=>(li.querySelector('a')||li).textContent.trim().replace(/\s+/g,' ')).filter(t=>t&&t.length<34&&!/todos|pre[çc]o/i.test(t));
 let k=0;const ph=()=>{if(document.activeElement===inp||inp.value)return;inp.placeholder='Experimente “'+cats[k++%cats.length]+'”'};if(cats.length){ph();setInterval(ph,2600)}
 const sg=()=>$('.js-search-form-suggestions');
 inp.addEventListener('focus',()=>{inp.placeholder='Digite um perfume, marca ou categoria';sg()&&sg().style.removeProperty('display')});
 inp.addEventListener('input',()=>{sg()&&sg().style.removeProperty('display')})}
const big=$('.js-head-row .header-icon-big'),amt=big&&big.querySelector('.js-cart-widget-amount');
if(amt){const upd=()=>big.classList.toggle('jk-has',(parseInt(amt.textContent,10)||0)>0);upd();new MutationObserver(upd).observe(amt,{childList:true,characterData:true,subtree:true})}
const read=li=>{const a=li.querySelector(':scope > a, :scope > div > a');const kids=[...li.querySelectorAll('li')].filter(x=>x.parentElement.closest('li')===li);return {t:a?a.textContent.trim().replace(/\s+/g,' '):'',href:a?a.href:'#',kids:kids.map(read).filter(k=>k.t)}};
const data=$$('.nav-desktop .js-desktop-nav-item').filter(li=>!li.parentElement.closest('.js-desktop-nav-item')).map(read).filter(d=>d.t);
const mega=(title,href,kids,kicker)=>`<div class="jk-mega"><div class="jk-mega-in"><div class="jk-side"><div class="jk-kicker">${kicker}</div><p class="jk-title">${esc(title)}</p>${href?`<a class="jk-all" href="${href}">Ver todos</a>`:''}</div><div class="jk-cols">${kids.map(k=>`<div class="jk-group"><a class="jk-sub" href="${k.href}">${esc(k.t)}</a>${k.kids.map(g=>`<a class="jk-sub3" href="${g.href}">${esc(g.t)}</a>`).join('')}</div>`).join('')}</div></div></div>`;
const item=d=>`<div class="jk-item${d.kids.length?' has-kids':''}"><a class="jk-link" href="${d.href}">${esc(d.t)}</a>${d.kids.length?mega(d.t,d.href,d.kids,'Categoria'):''}</div>`;
const headRow=$('.js-head-row');let nav=null;
if(headRow&&data.length){nav=document.createElement('nav');nav.id='jk-nav';headRow.after(nav);
 let tm;const bind=()=>nav.querySelectorAll('.jk-item.has-kids').forEach(it=>{it.onmouseenter=()=>{clearTimeout(tm);nav.querySelectorAll('.is-open').forEach(o=>o!==it&&o.classList.remove('is-open'));it.classList.add('is-open')};it.onmouseleave=()=>{tm=setTimeout(()=>it.classList.remove('is-open'),180)}});
 const fit=()=>{nav.innerHTML='<div class="jk-row"></div>';const row=nav.firstChild;row.innerHTML=data.map(item).join('');if(innerWidth<768)return;const items=[...row.children];
  const max=row.clientWidth-48,moreW=210;let used=0,cut=items.length;
  for(let i=0;i<items.length;i++){used+=items[i].offsetWidth;if(used>max-(i<items.length-1?moreW:0)){cut=i;break}}
  if(cut<items.length){items.slice(cut).forEach(e=>e.remove());const m=document.createElement('div');m.className='jk-item jk-more has-kids';m.innerHTML=`<a class="jk-link" href="#">Mais categorias<span>+</span></a>`+mega('Todas as categorias','',data.slice(cut),'Explore');row.appendChild(m);m.querySelector('.jk-link').onclick=e=>e.preventDefault()}
  bind()};
 await document.fonts.ready;fit();window.__jkfit=fit;let rz;addEventListener('resize',()=>{clearTimeout(rz);rz=setTimeout(fit,150)})}
const ov=document.createElement('div');ov.id='jk-dw-ov';const dw=document.createElement('aside');dw.id='jk-dw';
const acc=($('.js-head-row .js-header-utility-icon-only a')||{getAttribute:()=>'/account/login/'}).getAttribute('href');
dw.innerHTML=`<div class="dw-top"><img src="${logo?(logo.currentSrc||logo.src):''}" alt=""><button class="dw-x" aria-label="Fechar">${S(I.x,1.4)}</button></div><div class="dw-hello">Categorias</div><div class="dw-stage"></div><div class="dw-foot"><a href="${acc}">${S(I.user,1.2)}Minha conta</a><a href="#" class="dw-cart">${S(I.bag,1.2)}Sacola</a></div>`;
document.body.append(ov,dw);wrapLogo(dw.querySelector('.dw-top img'));
const stage=dw.querySelector('.dw-stage'),stack=[];
const rows=l=>l.map((d,i)=>d.kids.length?`<button class="dw-row" data-i="${i}" style="transition-delay:${Math.min(i,12)*35}ms">${esc(d.t)}<span class="dw-plus">${S(I.plus,1.5)}</span></button>`:`<a class="dw-row" href="${d.href}" style="transition-delay:${Math.min(i,12)*35}ms">${esc(d.t)}</a>`).join('');
const panel=(l,parent)=>{const p=document.createElement('div');p.className='dw-panel'+(parent?' dw-sub is-right':' is-cur');p.innerHTML=parent?`<button class="dw-back">${S(I.back)}Voltar</button><p class="dw-title">${esc(parent.t)}</p><a class="dw-all" href="${parent.href}">Ver tudo</a>${rows(l)}`:rows(l);
 p.addEventListener('click',e=>{const b=e.target.closest('button.dw-row');if(b){openP(l[+b.dataset.i]);return}if(e.target.closest('.dw-back'))back()});return p};
const openP=d=>{const cur=stack[stack.length-1],p=panel(d.kids,d);stage.appendChild(p);stack.push(p);requestAnimationFrame(()=>requestAnimationFrame(()=>{cur.classList.remove('is-cur');cur.classList.add('is-left');p.classList.remove('is-right');p.classList.add('is-cur')}))};
const back=()=>{if(stack.length<2)return;const p=stack.pop(),prev=stack[stack.length-1];p.classList.remove('is-cur');p.classList.add('is-right');prev.classList.remove('is-left');prev.classList.add('is-cur');setTimeout(()=>p.remove(),450)};
const reset=()=>{stage.innerHTML='';stack.length=0;const p=panel(data,null);stage.appendChild(p);stack.push(p)};
const show=()=>{reset();document.documentElement.classList.add('jk-dw-open')},hide=()=>document.documentElement.classList.remove('jk-dw-open');
dw.querySelector('.dw-x').onclick=hide;ov.onclick=hide;
dw.querySelector('.dw-cart').onclick=e=>{e.preventDefault();hide();setTimeout(()=>$('.js-head-row .utilities-container .js-modal-open-private')?.click(),300)};
const hb=$('.js-head-row .menu-container .js-modal-open-private');
if(hb)hb.addEventListener('click',e=>{if(innerWidth<768){e.preventDefault();e.stopImmediatePropagation();show()}},true);
document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;
 if(document.documentElement.classList.contains('jk-dw-open')){stack.length>1?back():hide();return}
 nav&&nav.querySelectorAll('.is-open').forEach(o=>o.classList.remove('is-open'));
 const sg=$('.js-search-form-suggestions'),inp=$('.js-head-row .js-search-input');
 if(sg)sg.style.display='none';if(inp&&document.activeElement===inp)inp.blur()});
const IB={entrega:'<path d="M4.5 9.5h15v10h-15z"/><path d="M3.5 6.5h17v3h-17z"/><path d="M12 6.5v13"/><path d="M12 6.5c-1.2-2.6-4.6-3-4.6-1 0 1.4 2.4 1 4.6 1zM12 6.5c1.2-2.6 4.6-3 4.6-1 0 1.4-2.4 1-4.6 1z"/>',cartao:'<rect x="3" y="6" width="18" height="12.5" rx="2"/><path d="M3 10h18"/><path d="M6.5 14.8h3.5"/><rect x="15" y="13.6" width="3" height="2.4" rx=".5"/>',seguro:'<path d="M12 3.2l7 2.6v5.4c0 4.3-2.9 7.8-7 9.4-4.1-1.6-7-5.1-7-9.4V5.8z"/><path d="M12 8.6l1.9 2.8L12 14.2l-1.9-2.8z"/>',atendimento:'<path d="M20 11.6c0 4.1-3.6 7.4-8 7.4-1.1 0-2.2-.2-3.2-.6L4.5 19.6l1.2-3.6C4.6 14.8 4 13.3 4 11.6 4 7.5 7.6 4.2 12 4.2s8 3.3 8 7.4z"/><path d="M8.6 11.6h.01M12 11.6h.01M15.4 11.6h.01" stroke-width="1.9"/>',troca:'<path d="M4.5 9.5A7.5 7.5 0 0 1 18 6.8M19.5 14.5A7.5 7.5 0 0 1 6 17.2"/><path d="M18.6 3.6l-.4 3.4-3.4-.4M5.4 20.4l.4-3.4 3.4.4"/>',pix:'<path d="M12 3.5l8.5 8.5-8.5 8.5L3.5 12z"/><path d="M12 8.2l3.8 3.8-3.8 3.8L8.2 12z"/>',original:'<circle cx="12" cy="9.5" r="5.5"/><path d="M9 14.2L7.6 20.5 12 18.4l4.4 2.1-1.4-6.3"/><path d="M10 9.6l1.4 1.4 2.8-2.8"/>'};
const byIcon={truck:'entrega','credit-card':'cartao',security:'seguro','whatsapp-line':'atendimento',whatsapp:'atendimento',returns:'troca',exchange:'troca',money:'pix',cash:'pix',star:'original',award:'original'};
const byText=[[/entreg|frete|envi|brasil/i,'entrega'],[/parcel|cart[aã]o|juros/i,'cartao'],[/segur|prote/i,'seguro'],[/atendimento|whats|contato/i,'atendimento'],[/troca|devolu/i,'troca'],[/pix|desconto|[aà] vista/i,'pix'],[/original|aut[eê]ntic|garantia/i,'original']];
const ibEl=$('.js-informative-banners');
if(ibEl){const deco=()=>ibEl.querySelectorAll('.swiper-slide').forEach(s=>{const nat=s.querySelector('[class*="js-informative-banner-icon"] > svg:not(.jk-svg), [class*="js-informative-banner-icon"] > img');if(!nat||s.querySelector('.jk-ib-ico'))return;
  const u=nat.querySelector&&nat.querySelector('use');const ref=u?(u.getAttribute('xlink:href')||u.getAttribute('href')||'').replace('#',''):'';
  let k=byIcon[ref]||(byText.find(([re])=>re.test(s.textContent))||[])[1];if(!k)return;
  const box=document.createElement('span');box.className='jk-ib-ico';box.innerHTML=`<svg class="jk-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.15" stroke-linecap="round" stroke-linejoin="round">${IB[k]}</svg>`;nat.classList.add('jk-ib-native');nat.parentNode.insertBefore(box,nat)});
 deco();new MutationObserver(deco).observe(ibEl,{childList:true,subtree:true});
 const sw=ibEl.swiper;if(sw){let hold=0;ibEl.addEventListener('touchstart',()=>hold=Date.now(),{passive:true});setInterval(()=>{if(innerWidth>=768||document.hidden||Date.now()-hold<6000)return;sw.isEnd?sw.slideTo(0,700):sw.slideNext(700)},3800)}}
addArrows('.js-swiper-home-prev, .js-swiper-home-next');
addArrows('[class*="js-products-"][class*="-container"] > .swiper-button-prev, [class*="js-products-"][class*="-container"] > .swiper-button-next');
addArrows('.section-testimonials-home .swiper-button-prev, .section-testimonials-home .swiper-button-next');
$$('[class*="js-products-"][class*="-container"] > .swiper-pagination').forEach(pg=>{if(pg.dataset.jk)return;pg.dataset.jk=1;
 const box=document.createElement('div');box.className='jk-prog';box.innerHTML='<span class="jk-num">01</span><span class="jk-track"><span class="jk-fill"></span></span><span class="jk-tot">01</span>';pg.after(box);pg.classList.add('jk-hide');
 const upd=()=>{const b=$$('.swiper-pagination-bullet',pg);const n=b.length||1;const i=Math.max(0,b.findIndex(x=>x.classList.contains('swiper-pagination-bullet-active')));box.style.display=n<2?'none':'flex';box.querySelector('.jk-num').textContent=pad(i+1);box.querySelector('.jk-tot').textContent=pad(n);box.querySelector('.jk-fill').style.width=((i+1)/n*100)+'%'};
 upd();new MutationObserver(upd).observe(pg,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});
 box.querySelector('.jk-track').addEventListener('click',e=>{const r=e.currentTarget.getBoundingClientRect();const b=$$('.swiper-pagination-bullet',pg);const k=Math.min(b.length-1,Math.floor((e.clientX-r.left)/r.width*b.length));b[k]&&b[k].click()})});
const CARD='.js-item-product';
const bagSvg='<svg class="jk-bag" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M5.6 8.8h12.8l-.9 11.4H6.5z"/><path d="M9.2 8.8V7.1a2.8 2.8 0 0 1 5.6 0v1.7"/><path d="M10.4 13.4c.5.7 1 1 1.6 1s1.1-.3 1.6-1"/></svg>';
const pixSvg='<svg class="jk-pix" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M12 2.8l9.2 9.2-9.2 9.2L2.8 12z"/><path d="M12 8l4 4-4 4-4-4z"/></svg>';
const num=t=>parseFloat((t||'').replace(/[^\d,]/g,'').replace(',','.'))||0;
window.jkDecoCards=(root=document)=>{document.querySelectorAll('.js-product-table').forEach(t=>{if(!t.classList.contains('js-products-grid-container'))t.classList.add('js-products-grid-container')});$$(CARD,root).forEach(c=>{if(c.closest('#quickshop-modal'))return;
 const b=c.querySelector('.js-payment-discount-price-product-container');
 if(b&&!b.querySelector('.jk-pix')){b.insertAdjacentHTML('afterbegin',pixSvg);const p=num(c.querySelector('.js-price-display')?.textContent),x=num(b.querySelector('.js-payment-discount-price-product')?.textContent);if(p&&x&&x<p){const off=Math.round((1-x/p)*100);if(off>0)b.insertAdjacentHTML('beforeend',`<span class="jk-pix-off">${off}% OFF</span>`)}}
 const q=c.querySelector('.product-item-quick-shop-modal-trigger');if(q&&!q.querySelector('.jk-bag'))q.insertAdjacentHTML('afterbegin',bagSvg);
 c.querySelectorAll('.product-item-link > .js-nubesdk-slot').forEach(s=>{if(!s.classList.contains('jk-notify')&&/avise/i.test(s.textContent))s.classList.add('jk-notify')})})};
jkDecoCards();let dcT;new MutationObserver(()=>{clearTimeout(dcT);dcT=setTimeout(()=>jkDecoCards(),300)}).observe(document.body,{childList:true,subtree:true});
const hs=$$('h2[class*="js-products-"][class*="-title"]');hs.forEach(h=>h.classList.add('jk-pre'));
const io=new IntersectionObserver(es=>es.forEach(en=>{if(en.isIntersecting){en.target.classList.remove('jk-pre');io.unobserve(en.target)}}),{threshold:.4});hs.forEach(h=>io.observe(h));
$$('.textbanner-image').forEach((im,i)=>{im.parentElement.classList.add('jk-tb-frame');im.style.animationDelay=(i*-1.6)+'s'});
const vs=$('.section-video-home');
if(vs){const t=vs.querySelector('.js-home-video-title');
 if(t&&!vs.querySelector('.jk-vkick')){const raw=t.textContent.trim(),i=raw.indexOf(':');if(i>0){const k=document.createElement('span');k.className='jk-vkick';k.textContent=raw.slice(0,i).trim();t.before(k);t.textContent=raw.slice(i+1).trim()}}
 const b=vs.querySelector('.js-home-video-button');if(b&&!b.querySelector('svg'))b.insertAdjacentHTML('beforeend','<svg viewBox="0 0 22 10" fill="none" stroke="currentColor" stroke-width="1.1" stroke-linecap="round" stroke-linejoin="round"><path d="M1 5h20M16.5 1L21 5l-4.5 4"/></svg>');
 const c=vs.querySelector('.js-home-video-container');const id=c&&(c.getAttribute('data-video')||c.getAttribute('data-video-url'));const v=vs.querySelector('.js-home-video');
 if(id&&v&&!v.querySelector('.jk-vbox')){const box=document.createElement('div');box.className='jk-vbox';
  box.innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${id}?autoplay=1&mute=1&loop=1&playlist=${id}&controls=0&modestbranding=1&playsinline=1&rel=0&iv_load_policy=3&disablekb=1&enablejsapi=1&origin=${encodeURIComponent(location.origin)}" allow="autoplay; encrypted-media; picture-in-picture" title="Vídeo"></iframe>`;v.appendChild(box);
  const f=box.querySelector('iframe');const cmd=(fn,args=[])=>f.contentWindow&&f.contentWindow.postMessage(JSON.stringify({event:'command',func:fn,args}),'*');
  const w=document.createElement('div');w.className='jk-vctl';
  w.innerHTML=`<button class="jk-pp" aria-label="Pausar vídeo"><svg class="pause" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"><path d="M9 6v12M15 6v12"/></svg><svg class="play" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linejoin="round"><path d="M8 5.5l11 6.5-11 6.5z"/></svg></button><button class="jk-snd" aria-label="Ativar som"><svg class="off" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M4 9.5h3.5L12 5.5v13l-4.5-4H4z"/><path d="M16 9.5l5 5M21 9.5l-5 5"/></svg><svg class="on" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M4 9.5h3.5L12 5.5v13l-4.5-4H4z"/><path d="M15.5 9a4 4 0 0 1 0 6M18 6.5a7.5 7.5 0 0 1 0 11"/></svg></button>`;box.appendChild(w);
  const pp=w.querySelector('.jk-pp'),sn=w.querySelector('.jk-snd');
  pp.onclick=()=>{const p=!pp.classList.contains('is-paused');pp.classList.toggle('is-paused',p);cmd(p?'pauseVideo':'playVideo')};
  sn.onclick=()=>{const on=!sn.classList.contains('is-on');sn.classList.toggle('is-on',on);if(on){cmd('unMute');cmd('setVolume',[80]);cmd('playVideo')}else cmd('mute')}}}
const ts=$('.section-testimonials-home');
if(ts){const star='<svg class="jk-st" viewBox="0 0 24 24" fill="currentColor"><path d="M12 3.2l2.6 5.6 6.1.7-4.5 4.2 1.2 6.1L12 16.8l-5.4 3 1.2-6.1-4.5-4.2 6.1-.7z"/></svg>';const notas=[];
 ts.querySelectorAll('.js-testimonial-slide').forEach(sl=>{const st=sl.querySelector('.js-testimonial-stars');if(!st)return;const m=st.className.match(/(?:^|\s)testimonial-stars-(\d)(?:\s|$)/);const n=m?+m[1]:st.querySelectorAll('svg:not(.jk-st)').length;if(!sl.classList.contains('swiper-slide-duplicate'))notas.push(n);if(!st.querySelector('.jk-stars')){const w=document.createElement('span');w.className='jk-stars';w.innerHTML=star.repeat(n);st.appendChild(w)}});
 if(notas.length&&!ts.querySelector('.jk-dep-sum')){const avg=notas.reduce((a,b)=>a+b,0)/notas.length;const d=document.createElement('div');d.className='jk-dep-sum';d.innerHTML=`<span class="jk-stars">${star.repeat(Math.round(avg))}</span><b>${avg.toFixed(1).replace('.',',')}</b><span>${notas.length} avaliações de clientes</span>`;ts.querySelector('.js-testimonial-main-title')?.after(d)}}
const is=$('.section-instafeed-home');const igA=is&&is.querySelector('a[href*="instagram.com"]');
if(igA&&!is.querySelector('.jk-fill')){const href=igA.href,handle='@'+href.replace(/\/+$/,'').split('/').pop();
 const a=document.createElement('a');a.className='jk-fill';a.href=href;a.target='_blank';a.rel='noopener';
 a.innerHTML=`<span class="jk-fill-kick">${S(I.ig,1.5)}Siga no Instagram</span><span class="jk-fill-word"><span class="o">${esc(handle)}</span><span class="f" aria-hidden="true">${esc(handle)}</span></span><span class="jk-fill-sub">Lançamentos, decants e bastidores em primeira mão · <b>toque para seguir</b></span>`;
 is.querySelector('.js-instagram-feed .container').appendChild(a);
 new IntersectionObserver((es,o)=>es.forEach(e=>{if(e.isIntersecting){a.classList.add('is-on');o.disconnect()}}),{threshold:.6}).observe(a)}
const ft=$('footer.js-footer');
if(ft&&!ft.querySelector('.jk-foot')){
 const links=$$('a[href]',ft);const wa=links.find(a=>/wa\.me|whatsapp/i.test(a.href)),tel=links.find(a=>/^tel:/i.test(a.getAttribute('href'))),mail=links.find(a=>/^mailto:/i.test(a.getAttribute('href')));
 const addr=$$('.footer-contact-info-container *',ft).filter(e=>!e.children.length&&!e.closest('a')).map(e=>e.textContent.trim()).find(t=>/[a-zà-ú].*,/i.test(t)&&t.length>12)||'';
 const menu=links.filter(a=>!/wa\.me|whatsapp|^tel:|^mailto:|instagram|facebook|tiktok|nuvemshop/i.test(a.getAttribute('href'))&&a.textContent.trim()&&!a.closest('.footer-payments-shipping-container')).map(a=>({t:a.textContent.trim().replace(/\s+/g,' '),h:a.href}));
 const groups=$$('.footer-nav-container .js-accordion-private-container',ft).map(c=>({t:(c.querySelector('.accordion-title')?.textContent||'').trim(),l:$$('a[href]:not(.accordion-title)',c).filter(a=>a.textContent.trim()).map(a=>({t:a.textContent.trim().replace(/\s+/g,' '),h:a.href}))})).filter(g=>g.l.length);
 const SOC={instagram:['Instagram',I.ig],facebook:['Facebook','<path d="M14.6 8.2h2.1V4.9h-2.5c-2.8 0-4 1.7-4 4.2v2.1H7.9v3.3h2.3v6.9h3.4v-6.9h2.5l.4-3.3h-2.9V9.4c0-.8.3-1.2 1-1.2z"/>'],youtube:['YouTube','<rect x="2.8" y="5.8" width="18.4" height="12.4" rx="3.6"/><path d="M10.2 9.3l4.8 2.7-4.8 2.7z"/>'],tiktok:['TikTok','<path d="M14 3.6v11.2a3.3 3.3 0 1 1-3.3-3.3"/><path d="M14 3.6c.4 2.6 2.1 4.2 4.7 4.4"/>'],pinterest:['Pinterest','<circle cx="12" cy="12" r="8.6"/><path d="M11.2 9.2l-2.4 11M9.6 13.5c.6 1 1.6 1.4 2.7 1.3 2.4-.2 3.9-2.4 3.6-4.8-.3-2.2-2.4-3.5-4.6-3.2-2.6.4-4 2.6-3.3 4.9"/>'],'x.com':['X','<path d="M5 4.5l14 15M19 4.5l-14 15"/>'],twitter:['X','<path d="M5 4.5l14 15M19 4.5l-14 15"/>']};
 const socs=links.filter(a=>!a.textContent.trim()&&a.closest('.footer-contact-info-container')).map(a=>{const k=Object.keys(SOC).find(k=>a.href.includes(k));return k?`<a href="${a.href}" target="_blank" rel="noopener" aria-label="${SOC[k][0]}">${S(SOC[k][1])}</a>`:''}).join('');
 const copy=$$('*',ft).map(e=>e.childNodes.length===1&&e.textContent).find(t=>t&&/copyright/i.test(t))||'';
 const cn=((copy.match(/\d{2}\.?\d{3}\.?\d{3}\/?\d{4}-?\d{2}/)||[])[0]||'').replace(/\D/g,'');const cnpj=cn.length===14?cn.replace(/(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/,'$1.$2.$3/$4-$5'):'';
 const empresa=(copy.replace(/copyright/i,'').split(/[-–]/)[0]||'').trim();
 const fmt=n=>{let d=String(n).replace(/\D/g,'');if(d.startsWith('55')&&d.length>11)d=d.slice(2);return d.length===11?`(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`:d.length===10?`(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`:n};
 const ig=igA?igA.href:'';const lsrc=logo?(logo.currentSrc||logo.src):'';
 const desc=($('meta[name="description"]')?.content||'');const dtx=desc.length>150?desc.slice(0,150).replace(/\s+\S*$/,'')+'…':desc;
 const nf=ft.querySelector('form'),nIn=nf&&nf.querySelector('input[type=email], input[name*=mail]');const pays=$$('.footer-payments-shipping-container img',ft);
 const w=document.createElement('div');w.className='jk-foot';
 w.innerHTML=`<div class="jk-f-main"><div class="jk-f-in jk-f-frame"><div class="jk-f-news"><div><h3>Clube da Jack</h3><p>Lançamentos, cupons e decants novos chegam primeiro no seu e-mail.</p></div><div><div class="jk-strip"><span class="jk-strip-lbl">Seu e-mail</span><span class="jk-strip-slot"></span><button type="button" class="jk-send"><span>Quero</span>${S(I.arrow)}</button><i class="jk-strip-tip"></i></div><p class="jk-strip-msg"></p></div></div><div class="jk-f-cols"><div class="jk-f-brand"><a class="jk-f-logo" href="/" aria-label="Página inicial" style="-webkit-mask-image:url('${lsrc}');mask-image:url('${lsrc}')"></a>${dtx?`<p>${esc(dtx)}</p>`:''}<div class="jk-f-soc">${socs}${wa?`<a href="${wa.href}" target="_blank" rel="noopener" aria-label="WhatsApp">${S(I.wa)}</a>`:''}</div></div>${groups.map(g=>`<div class="jk-f-col"><h4>${esc(g.t)}</h4>${g.l.map(m=>`<a class="jk-f-link" href="${m.h}">${esc(m.t)}</a>`).join('')}</div>`).join('')}<div class="jk-f-col jk-f-contact"><h4>Atendimento</h4>${wa?`<a class="jk-f-ct" href="${wa.href}" target="_blank" rel="noopener">${S(I.wa)}<span><small>WhatsApp</small><b>${fmt((wa.href.match(/wa\.me\/(\d+)/)||[])[1]||'')}</b></span></a>`:''}${tel?`<a class="jk-f-ct" href="tel:${tel.getAttribute('href').replace(/\D/g,'')}">${S(I.tel)}<span><small>Telefone</small><b>${fmt(tel.getAttribute('href'))}</b></span></a>`:''}${mail?`<a class="jk-f-ct" href="${mail.getAttribute('href')}">${S(I.mail)}<span><small>E-mail</small><b>${esc(mail.textContent.trim())}</b></span></a>`:''}${addr?`<div class="jk-f-ct">${S(I.pin)}<span><small>Endereço</small>${esc(addr)}</span></div>`:''}</div><div class="jk-f-col jk-f-paycol"><h4>Pagamento</h4><div class="jk-f-pay"></div><div class="jk-f-safe">${S(I.lock)}Compra 100% segura</div></div></div></div></div><div class="jk-f-bar"><div class="jk-f-in"><div class="jk-f-legal">© ${new Date().getFullYear()} <b>${esc(empresa)}</b>${cnpj?`<span>·</span>CNPJ ${cnpj}`:''}<span>·</span>Todos os direitos reservados</div><div class="jk-f-cred"><div id="lari-wm-box"><a id="lari-wm" href="https://wa.me/message/IGGSZJCTRU67K1" target="_blank" rel="noopener" aria-label="Criado por Sites com a Lari - falar no WhatsApp"><span>Criado por</span><span class="lw"></span></a></div></div></div></div>`;
 ft.appendChild(w);const pay=w.querySelector('.jk-f-pay');pays.forEach(i=>pay.appendChild(i.cloneNode(true)));
 if(nIn){nIn.setAttribute('placeholder','Digite seu melhor e-mail');w.querySelector('.jk-strip-slot').replaceWith(nIn);
  w.querySelector('.jk-send').onclick=()=>{if(!nIn.value||!nIn.checkValidity()){w.querySelector('.jk-strip-msg').textContent='Confere o e-mail, por favor.';nIn.focus();return}const sb=nf.querySelector('[type=submit]');sb?sb.click():nf.requestSubmit()};
  nIn.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();w.querySelector('.jk-send').click()}})}}
try{const t=JSON.parse(localStorage.getItem('jkTiers')||'null');if(t&&t.length>1&&window.JK_PROMO==null)window.__jkT=t}catch(e){}window.JK_PROMO=window.JK_PROMO||{nome:'Compre mais, pague menos',degraus:[[1,0],[2,5],[3,8],[4,11],[5,14],[10,20]],conta:n=>/decant|fracionad/i.test(n)};
if(window.__jkT)JK_PROMO.degraus=window.__jkT;const D=JK_PROMO.degraus;
const tierOf=n=>{let p=0;D.forEach(([q,v])=>{if(n>=q)p=v});return p};window.jkTierOf=tierOf;
const posOf=n=>{if(n<=0)return 0;const i=D.findIndex(([q])=>q>n);if(i===-1)return 100;const [q0]=D[i-1],[q1]=D[i];const seg=100/(D.length-1);return (i-1)*seg+seg*((n-q0)/(q1-q0))};window.jkPos=posOf;
window.jkMeterHTML=n=>{const p=tierOf(n),nx=D.find(([q])=>q>n),f=nx?nx[0]-n:0;
 const msg=n===0?`Adicione decants e o desconto aparece sozinho, até <b>20% OFF</b>.`:nx?`${p?`Seus decants já estão com <b>${p}% OFF</b>. `:''}Mais <b>${f} decant${f>1?'s':''}</b> e vira <b>${nx[1]}% OFF</b>.`:`Desconto máximo liberado: <b>20% OFF</b> em todos os decants.`;
 const vial=(fill,on)=>{const h=Math.round(30*fill);return `<svg viewBox="0 0 18 44"><rect class="cap" x="5" y="0" width="8" height="8" rx="1.2"/><rect x="7" y="8" width="4" height="3" fill="${on?'var(--accent-color)':'color-mix(in srgb,var(--header-featured-link-foreground) 55%,#fff)'}"/><rect class="glass" x="2.5" y="11" width="13" height="32" rx="3"/><rect class="liq" x="4" y="${41.5-h}" width="10" height="${h}" rx="1.8" fill="url(#jkLiq)"/></svg>`};
 const prevQ=i=>i?D[i-1][0]:0;const seg=100/(D.length-1);
 return `<div class="jk-m2"><svg width="0" height="0" style="position:absolute"><defs><linearGradient id="jkLiq" x1="0" y1="1" x2="0" y2="0"><stop offset="0" stop-color="var(--accent-color)"/><stop offset="1" stop-color="var(--header-featured-link-foreground)"/></linearGradient></defs></svg><div class="jk-m2-k">${n} decant${n===1?'':'s'} na sacola</div><div class="jk-m2-t">${JK_PROMO.nome}</div><div class="jk-m2-row">${D.map(([q,v],i)=>{const on=n>=q;const fill=on?1:(nx&&nx[0]===q?Math.max(0,(n-prevQ(i))/(q-prevQ(i))):0);return `<div class="jk-v vial-only${on?' on':''}${on&&p===v?' now':''}">${vial(fill,on)}</div>`}).join('')}</div><div class="jk-m2-track"><i style="width:${posOf(n)}%"></i>${D.map(([q],k)=>`<u class="${n>=q?'on':''}" style="left:${k*seg}%"></u>`).join('')}</div><div class="jk-m2-labels">${D.map(([q,v])=>`<div class="jk-v${n>=q?' on':''}"><b>${v?v+'%':'—'}</b><em>${q}${q>=5?'+':''} un.</em></div>`).join('')}</div><p class="jk-m2-msg">${msg}</p></div>`};
const rowName=r=>$$('a,div,span,p',r).filter(e=>!e.children.length&&/[a-zà-ú]{3}/i.test(e.textContent)&&!/remover|até \d+%|off|r\$/i.test(e.textContent)).map(e=>e.textContent.trim()).sort((a,b)=>b.length-a.length)[0]||'';
window.jkCount=()=>{const list=$('.js-ajax-cart-list');if(list)return $$('.js-cart-item',list).reduce((a,r)=>a+(JK_PROMO.conta(rowName(r))?(parseInt(r.querySelector('input.js-cart-quantity-input')?.value,10)||1):0),0);return ((window.LS&&LS.cart&&LS.cart.items)||[]).reduce((a,x)=>a+(JK_PROMO.conta(x.name||'')?(+x.quantity||1):0),0)};
window.jkCartMeter=()=>{const list=$('.js-ajax-cart-list');if(!list)return;let m=$('.jk-cart-meter');if(!m){m=document.createElement('div');m.className='jk-cart-meter';list.parentElement.insertBefore(m,list)}m.innerHTML=jkMeterHTML(jkCount())};
const pill=document.createElement('button');pill.id='jk-pill';const pop=document.createElement('div');pop.id='jk-pop';document.body.append(pill,pop);
window.jkPill=()=>{const n=jkCount(),pc=tierOf(n),nx=D.find(([q])=>q>n);pill.innerHTML=`<span class="pv"><i style="width:${posOf(n)}%"></i></span><span class="txt">${n===0?`Decants: até <b>20% OFF</b>`:nx?`<b>${pc?pc+'% OFF':'1 decant'}</b> · +${nx[0]-n} p/ ${nx[1]}%`:`<b>20% OFF</b> no máximo`}</span>`;pop.innerHTML=jkMeterHTML(n)};
pill.onclick=e=>{e.stopPropagation();jkPill();pop.classList.toggle('open')};document.addEventListener('click',e=>{if(!pop.contains(e.target))pop.classList.remove('open')});
let pT;addEventListener('scroll',()=>{pill.classList.add('hide');pop.classList.remove('open');clearTimeout(pT);pT=setTimeout(()=>{const f=$('.jk-foot');pill.classList.toggle('hide',!!(f&&f.getBoundingClientRect().top<innerHeight-40))},500)},{passive:true});
const refresh=()=>{clearTimeout(window.__jkRf);window.__jkRf=setTimeout(()=>{jkCartMeter();jkPill()},250)};
jkCartMeter();jkPill();
const list=$('.js-ajax-cart-list');if(list){new MutationObserver(refresh).observe(list,{childList:true,subtree:true});list.addEventListener('input',refresh,true);list.addEventListener('change',refresh,true);list.addEventListener('click',()=>setTimeout(refresh,600),true)}
amt&&new MutationObserver(()=>setTimeout(refresh,400)).observe(amt,{childList:true,characterData:true,subtree:true});
const Q=$('#quickshop-modal');
if(Q){const qs=()=>{if(!Q.classList.contains('modal-show'))return;setTimeout(()=>{
  const b=Q.querySelector('.js-payment-discount-price-product-container');if(b){b.querySelector('.jk-pix')?.remove();b.querySelector('.jk-pix-off')?.remove();b.insertAdjacentHTML('afterbegin',pixSvg);const p=num(Q.querySelector('.js-price-display')?.textContent),x=num(b.querySelector('.js-payment-discount-price-product')?.textContent);if(p&&x&&x<p)b.insertAdjacentHTML('beforeend',`<span class="jk-pix-off">${Math.round((1-x/p)*100)}% OFF</span>`)}
  Q.querySelector('.jk-qs-meter')?.remove();const name=Q.querySelector('.js-item-name')?.textContent||'';
  if(JK_PROMO.conta(name)){const n=jkCount()+1,pc=tierOf(n);const d=document.createElement('div');d.className='jk-qs-meter';d.innerHTML=`<p class="jk-qs-tip">${pc?`Com este decant, sua sacola vai para ${pc}% OFF ✦`:`Leve mais um e ganhe 5% OFF nos dois ✦`}</p>`+jkMeterHTML(n);const v=Q.querySelector('.js-product-variants');(v?v.before(d):(Q.querySelector('.js-product-form')||Q.querySelector('.modal-body')).appendChild(d))}},800)};
 new MutationObserver(qs).observe(Q,{attributes:true,attributeFilter:['class']})}
const M=$('#related-products-notification');
if(M){const dress=()=>{if(!M.classList.contains('modal-show')){if(document.body.classList.contains('jk-added-on'))document.body.classList.remove('jk-added-on');return}
  if(M.__jkDressing)return;M.__jkDressing=1;setTimeout(()=>M.__jkDressing=0,900);if(!M.classList.contains('jk-added'))M.classList.add('jk-added');if(!document.body.classList.contains('jk-added-on'))document.body.classList.add('jk-added-on');
  const box=M.querySelector('.js-alert-add-to-cart-private > div:last-child'),vc=M.querySelector('.js-open-cart-modal');
  if(box&&vc&&!box.querySelector('.jk-add-btns')){const w=document.createElement('div');w.className='jk-add-btns';const k=document.createElement('button');k.type='button';k.className='jk-keep';k.textContent='Continuar';k.onclick=()=>M.querySelector('.modal-close').click();vc.textContent='Ver sacola';w.append(k,vc);box.appendChild(w)}
  setTimeout(()=>{M.querySelector('.jk-add-meter')?.remove();const n=jkCount();if(n>0){const d=document.createElement('div');d.className='jk-add-meter';d.innerHTML=jkMeterHTML(n);M.querySelector('.modal-body').appendChild(d)}refresh()},600);
  M.querySelector('.jk-add-timer')?.remove();const tm=document.createElement('i');tm.className='jk-add-timer';tm.style.setProperty('--dur','7s');M.appendChild(tm);
  tm.addEventListener('animationend',()=>{if(M.classList.contains('modal-show'))M.querySelector('.modal-close').click()});M.ontouchstart=()=>{if(!M.classList.contains('jk-hold'))M.classList.add('jk-hold')}};
 new MutationObserver(dress).observe(M,{attributes:true,attributeFilter:['class']})}

return 'ok'})().then(async()=>{;(()=>{if(window.__jkToast)return;window.__jkToast=1;
const N=document.querySelector('.js-alert-add-to-cart-private');if(!N)return;
const T=document.createElement('div');T.id='jk-toast';document.body.appendChild(T);let last=window.jkCount?jkCount():0,tm;
const close=()=>{T.classList.remove('show');clearTimeout(tm)};
const open=()=>{const img=N.querySelector('.js-cart-notification-item-image-private'),nm=(N.querySelector('.js-cart-notification-item-name-private')||{}).textContent||'',vr=(N.querySelector('.js-cart-notification-item-variant-private')||{}).textContent||'',pr=(N.querySelector('.js-cart-notification-item-price-private')||{}).textContent||'';
 const dec=window.JK_PROMO&&JK_PROMO.conta(nm);setTimeout(()=>{const n=jkCount(),up=dec&&jkTierOf(n)>jkTierOf(last);last=n;
  T.className='';T.innerHTML='<button class="x" aria-label="Fechar">×</button><p class="jk-unlock">✦ Você desbloqueou '+jkTierOf(n)+'% OFF nos decants</p><div class="jk-t-item">'+(img?'<span class="jk-t-img"><img src="'+(img.currentSrc||img.src)+'" alt=""></span>':'')+'<div><small>Adicionado à sacola</small><b>'+nm.trim()+'</b>'+(vr.trim()?'<em>'+vr.trim()+'</em>':'')+'<span class="jk-t-pr">'+pr.trim()+'</span></div></div>'+(dec?'<div class="jk-t-meter">'+jkMeterHTML(n)+'</div>':'')+'<div class="jk-t-btns"><button type="button" class="jk-keep">Continuar</button><button type="button" class="jk-see">Ver sacola</button></div><i class="jk-t-bar"></i>';
  if(up)T.classList.add('up');requestAnimationFrame(()=>T.classList.add('show'));
  T.querySelector('.x').onclick=close;T.querySelector('.jk-keep').onclick=close;T.querySelector('.jk-see').onclick=()=>{close();document.querySelector('.js-head-row .utilities-container .js-modal-open-private, .js-head-row [data-toggle="#modal-cart"]')?.click()};
  clearTimeout(tm);tm=setTimeout(close,7000);T.onmouseenter=()=>{clearTimeout(tm);T.classList.add('hold')};T.onmouseleave=()=>{T.classList.remove('hold');tm=setTimeout(close,3000)};T.ontouchstart=()=>{clearTimeout(tm);T.classList.add('hold')};
  window.jkPill&&jkPill()},450)};
let was=N.classList.contains('notification-hidden');new MutationObserver(()=>{const h=N.classList.contains('notification-hidden');if(was&&!h&&!document.querySelector('#related-products-notification.modal-show'))open();was=h}).observe(N,{attributes:true,attributeFilter:['class']});
})();;(async()=>{if(window.__jkSobre)return;window.__jkSobre=1;
const FOTO='https://i.ibb.co/LDQk9B88/IMG-4955-2.jpg';
const a=[...document.querySelectorAll('footer.js-footer a[href]')].find(x=>/sobre|quem somos|nossa hist|a marca/i.test(x.textContent));if(!a)return;
const ts=document.querySelector('.section-testimonials-home');const anchor=ts||document.querySelector('.section-instafeed-home');if(!anchor)return;
const u=new URL(a.href,location.href);const pv=new URLSearchParams(location.search).get('preview_theme_installation_id');if(pv)u.searchParams.set('preview_theme_installation_id',pv);
let d;try{d=new DOMParser().parseFromString(await fetch(u).then(r=>r.text()),'text/html')}catch(e){return}
const box=d.querySelector('.user-content');if(!box)return;
const ps=[...box.querySelectorAll('p,div')].filter(p=>!p.children.length||p.tagName==='P').map(p=>p.textContent.replace(/\s+/g,' ').trim()).filter(t=>t.length>40);
let txt=ps.slice(0,2).join(' ');if(txt.length>330)txt=txt.slice(0,330).replace(/\s+\S*$/,'')+'…';
const img=box.querySelector('img');const foto=img?img.src:FOTO;const titulo=(d.querySelector('h1')||{}).textContent||a.textContent;
const s=document.createElement('section');s.className='jk-sobre';
s.innerHTML='<div class="container"><div class="jk-sb-in"><a class="jk-sb-ph" href="'+u+'" aria-label="'+a.textContent.trim()+'"><span class="jk-sb-arch"><img src="'+foto+'" alt="" loading="lazy"></span><span class="jk-sb-sig">'+titulo.trim()+'</span></a><div class="jk-sb-tx"><span class="jk-sb-k">'+a.textContent.trim()+'</span><h2 class="jk-sb-t">Uma história<br>em cada fragrância</h2><span class="jk-sb-rule"><i></i></span><p>'+txt+'</p><a class="jk-sb-more" href="'+u+'"><span>Ver mais da nossa história</span><svg viewBox="0 0 22 10" fill="none" stroke="currentColor" stroke-width="1.1" stroke-linecap="round" stroke-linejoin="round"><path d="M1 5h20M16.5 1L21 5l-4.5 4"/></svg></a></div></div></div>';
anchor.after(s);
new IntersectionObserver((es,o)=>es.forEach(e=>{if(e.isIntersecting){s.classList.add('is-in');o.disconnect()}}),{threshold:.25}).observe(s);
})();;(()=>{const body=document.querySelector('section.category-body');if(!body||body.dataset.jk)return;body.dataset.jk=1;document.body.classList.add('jk-cat');
const C=body.querySelector(':scope > .container');const head=C&&C.querySelector(':scope > .grid.grid-md-auto');if(!head)return;head.classList.add('jk-cat-head');
const h1=head.querySelector('h1');const cnt=head.querySelector('h1 + div');const n=cnt?cnt.textContent.trim():'';
const path=p=>{try{return new URL(p,location.href).pathname.replace(/\/+$/,'')}catch(e){return ''}};const here=path(location.href);
const navLis=[...document.querySelectorAll('.nav-desktop li')];const own=li=>li.querySelector(':scope > a, :scope > div > a');
const me=navLis.find(li=>own(li)&&path(own(li).href)===here);const kidsOf=li=>[...li.querySelectorAll('li')].filter(x=>x.parentElement.closest('li')===li).map(own).filter(Boolean);
let list=[],active=null;if(me){list=kidsOf(me);if(!list.length){const par=me.parentElement.closest('li');if(par){list=kidsOf(par);active=here}}}
if(!list.length)list=[...document.querySelectorAll('.filters-categories-container ul a')];
const uniq=[];list.forEach(a=>{const t=a.textContent.trim().replace(/\s+/g,' ');if(t&&!uniq.some(x=>x.t===t))uniq.push({t,h:a.href})});
if(uniq.length){const w=document.createElement('nav');w.className='jk-subs';const MAX=8;
 w.innerHTML=uniq.map((x,k)=>'<a href="'+x.h+'"'+(path(x.h)===active?' class="on"':'')+(k>=MAX?' data-x="1"':'')+'>'+x.t+'</a>').join('')+(uniq.length>MAX?'<button type="button" class="jk-subs-more">+ '+(uniq.length-MAX)+' categorias</button>':'');
 head.firstElementChild.appendChild(w);const mb=w.querySelector('.jk-subs-more');if(mb)mb.onclick=()=>{w.classList.add('open');mb.remove()}}
const sortG=head.querySelector('.js-sort-by-private')?.closest('.form-group');
const grid=C.querySelector(':scope > .grid.grid-md-auto-4, :scope > .grid:last-child');
const bar=document.createElement('div');bar.className='jk-cat-bar';bar.innerHTML='<span class="jk-cat-n">'+n+'</span>';
const main=C.querySelector('.js-product-table')?.parentElement;if(main){main.prepend(bar);if(sortG)bar.appendChild(sortG)}
document.querySelectorAll('.js-price-filter-input').forEach(i=>{const b=i.closest('.form-group')?.parentElement;if(b&&!b.classList.contains('jk-price-f'))b.classList.add('jk-price-f')});document.querySelectorAll('.checkbox-text').forEach(t=>{if(t.querySelector('.jk-q'))return;t.innerHTML=t.innerHTML.replace(/\s*\((\d+)\)\s*$/,' <i class="jk-q">$1</i>')});
})();;(()=>{const SP=document.getElementById('single-product');if(!SP||SP.dataset.jk)return;SP.dataset.jk=1;document.body.classList.add('jk-pdp');
const $=s=>SP.querySelector(s);const info=$('.product-info > div');if(!info)return;
const sold=[...info.children].find(e=>/vendid/i.test(e.textContent)&&e.textContent.length<40);if(sold){sold.classList.add('jk-sold');sold.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linejoin="round"><path d="M12 3c1 3.5 5 5.5 5 10a5 5 0 0 1-10 0c0-2 1-3.4 2-4.4.2 1.6 1 2.6 2 3 0-3 .3-6 1-8.6z"/></svg><span>'+sold.textContent.trim().replace(/\s+/g,' ')+'</span>'}
const pix=$('.product-info .js-payment-discount-price-product-container');const num=t=>parseFloat((t||'').replace(/[^\d,]/g,'').replace(',','.'))||0;
const decoPix=()=>{if(!pix)return;pix.querySelector('.jk-pix')?.remove();pix.querySelector('.jk-pix-off')?.remove();pix.insertAdjacentHTML('afterbegin','<svg class="jk-pix" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"><path d="M12 2.8l9.2 9.2-9.2 9.2L2.8 12z"/><path d="M12 8l4 4-4 4-4-4z"/></svg>');const p=num($('#price_display')?.textContent),x=num(pix.querySelector('.js-payment-discount-price-product')?.textContent);if(p&&x&&x<p)pix.insertAdjacentHTML('beforeend','<span class="jk-pix-off">'+Math.round((1-x/p)*100)+'% OFF</span>')};
decoPix();const pd=$('#price_display');pd&&new MutationObserver(()=>setTimeout(decoPix,50)).observe(pd,{childList:true,characterData:true,subtree:true});
const buyIn=$('#product_form input.js-addtocart.js-prod-submit-form');if(buyIn&&!buyIn.parentElement.querySelector('.jk-buy-ico')){buyIn.parentElement.classList.add('jk-buy-wrap');buyIn.insertAdjacentHTML('afterend','<svg class="jk-buy-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M5.6 8.8h12.8l-.9 11.4H6.5z"/><path d="M9.2 8.8V7.1a2.8 2.8 0 0 1 5.6 0v1.7"/><path d="M10.4 13.4c.5.7 1 1 1.6 1s1.1-.3 1.6-1"/></svg>')}
const promo=$('.js-product-promo-container');let tiers=null;
if(promo){const rows=[...promo.querySelectorAll('tr')].map(tr=>{const off=parseInt(tr.querySelector('th')?.textContent,10),q=parseInt((tr.querySelector('td')?.textContent.match(/(\d+)\s*unidade/)||[])[1],10);return off&&q?[q,off]:null}).filter(Boolean).sort((a,b)=>a[0]-b[0]);
 if(rows.length){tiers=[[1,0],...rows];window.JK_PROMO.degraus.splice(0,99,...tiers);try{localStorage.setItem('jkTiers',JSON.stringify(tiers))}catch(e){}
  const nome=(promo.querySelector('h4,.label')?.textContent||'').trim()||JK_PROMO.nome;promo.classList.add('jk-hide-native');
  const box=document.createElement('div');box.className='jk-pdp-promo';const grid=buyIn&&buyIn.closest('.grid');
  const paint=()=>{const n=jkCount(),q=parseInt($('.js-quantity input')?.value,10)||1,t=n+q,pc=jkTierOf(t),cur=jkTierOf(n);
   box.innerHTML='<p class="jk-pp-tip">'+(pc>cur?'Levando '+(q>1?'estes '+q:'este')+', sua sacola de decants vai para <b>'+pc+'% OFF</b> ✦':pc?'Sua sacola de decants já está com <b>'+pc+'% OFF</b>':'Leve 2 decants (podem ser diferentes) e ganhe <b>'+(tiers[1]?tiers[1][1]:5)+'% OFF</b>')+'</p>'+jkMeterHTML(t).replace(/<div class="jk-m2-k">[^<]*<\/div>/,'<div class="jk-m2-k">'+t+' decant'+(t>1?'s':'')+' contando com este</div>').replace(/<div class="jk-m2-t">[^<]*<\/div>/,'<div class="jk-m2-t">'+nome.replace(/!$/,'')+'</div>')};
  paint();(grid||promo).after(box);const qi=$('.js-quantity');qi&&qi.addEventListener('click',()=>setTimeout(paint,80));qi&&qi.addEventListener('input',paint);
  const amt=document.querySelector('.js-cart-widget-amount');amt&&new MutationObserver(()=>setTimeout(paint,500)).observe(amt,{childList:true,characterData:true,subtree:true});}}
const shipB=[...info.children].find(e=>e.querySelector&&e.querySelector('.js-shipping-calculator-form, [name="zipcode"], .js-shipping-input'));
const order=()=>{const cg=buyIn&&buyIn.closest('.grid');if(!cg)return;let ref=cg;if(shipB){ref.after(shipB);shipB.classList.add('jk-ship');ref=shipB}const pp=SP.querySelector('.jk-pdp-promo');if(pp){ref.after(pp);ref=pp}const mf=$('#MF_product_save');if(mf){ref.after(mf)}};
const descB=SP.querySelector('.w-md-60');const imgs=SP.querySelector('.product-images');const home=descB&&descB.parentElement,mark=document.createComment('jk-desc');descB&&descB.before(mark);
const placeDesc=()=>{if(!descB||!imgs)return;if(innerWidth>=768){if(descB.parentElement!==imgs){imgs.appendChild(descB);descB.classList.add('jk-desc-side')}}else if(descB.parentElement===imgs){mark.after(descB);descB.classList.remove('jk-desc-side')}};
placeDesc();addEventListener('resize',placeDesc);setTimeout(order,0);const rel=document.querySelector('.js-related-products .js-swiper-related');if(rel)rel.classList.add('js-products-related-container');
const ph=$('.js-swiper-product .swiper-slide img');const nm=$('.js-product-name');
if(buyIn&&nm){const bar=document.createElement('div');bar.id='jk-buybar';bar.innerHTML='<div class="jk-bb-in">'+(ph?'<span class="jk-bb-img"><img src="'+(ph.currentSrc||ph.src)+'" alt=""></span>':'')+'<div class="jk-bb-tx"><b>'+nm.textContent.trim()+'</b><span class="jk-bb-pr"></span></div><button type="button" class="jk-bb-btn"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M5.6 8.8h12.8l-.9 11.4H6.5z"/><path d="M9.2 8.8V7.1a2.8 2.8 0 0 1 5.6 0v1.7"/></svg><span>Comprar</span></button></div>';document.body.appendChild(bar);
 const pr=()=>{const v=$('.js-insta-variation-label')?.textContent.trim();bar.querySelector('.jk-bb-pr').innerHTML=(pd?pd.textContent.trim():'')+(v?' <i>· '+v+'</i>':'')};pr();pd&&new MutationObserver(pr).observe(pd,{childList:true,characterData:true,subtree:true});$('.js-product-variants')?.addEventListener('click',()=>setTimeout(pr,120));
 bar.querySelector('.jk-bb-btn').onclick=()=>{if(buyIn.offsetParent&&!buyIn.disabled&&buyIn.closest('.cart-button-container')&&getComputedStyle(buyIn).display!=='none'){buyIn.click()}else{buyIn.scrollIntoView({behavior:'smooth',block:'center'})}};
 new IntersectionObserver(es=>es.forEach(e=>{const past=!e.isIntersecting&&e.boundingClientRect.top<0;document.body.classList.toggle('jk-bb-on',past)}),{threshold:0}).observe(buyIn.closest('.grid')||buyIn)}
})();;(()=>{if(window.jkVials)return;
window.jkVials=(root=document)=>{root.querySelectorAll('.js-product-variants-group').forEach(g=>{const bs=[...g.querySelectorAll('.js-insta-variant')];const ml=b=>{const m=(b.textContent||'').match(/(\d+(?:[.,]\d+)?)\s*ml/i);return m?parseFloat(m[1].replace(',','.')):null};
 if(bs.length<1||bs.some(b=>ml(b)===null))return;const vals=[...new Set(bs.map(ml))].sort((a,b)=>a-b);
 bs.forEach(b=>{if(b.querySelector('.jk-vial'))return;const v=ml(b),k=vals.indexOf(v),n=vals.length;const H=Math.round(22+(n>1?k/(n-1):1)*10);
  const W=Math.round(H*18/44);b.classList.add('jk-vbtn');b.insertAdjacentHTML('afterbegin','<svg class="jk-vial" style="width:'+W+'px!important;height:'+H+'px!important" width="'+W+'" height="'+H+'" viewBox="0 0 18 44" fill="none"><rect class="c" x="5" y="0" width="8" height="8" rx="1.2"/><rect class="n" x="7" y="8" width="4" height="3"/><rect class="g" x="2.5" y="11" width="13" height="32" rx="3"/><rect class="l" x="4" y="20" width="10" height="21.5" rx="1.8"/><rect class="s" x="5.2" y="22" width="1.6" height="15" rx=".8"/></svg>')})})};
jkVials();const Q=document.getElementById('quickshop-modal');Q&&new MutationObserver(()=>setTimeout(()=>jkVials(Q),300)).observe(Q,{attributes:true,attributeFilter:['class']});
})();;(()=>{if(!document.getElementById('jk-buybar')||window.__jkBbF)return;window.__jkBbF=1;let t;addEventListener('scroll',()=>{clearTimeout(t);t=setTimeout(()=>{const f=document.querySelector('.jk-foot');const on=!!(f&&f.getBoundingClientRect().top<innerHeight-60);if(document.body.classList.contains('jk-bb-foot')!==on)document.body.classList.toggle('jk-bb-foot',on)},80)},{passive:true})})();;(()=>{if(!document.body.classList.contains('template-page')||document.body.classList.contains('jk-inst'))return;const uc=document.querySelector('.container > .user-content');const ph=document.querySelector('section.page-header');if(!uc||!ph)return;document.body.classList.add('jk-inst');uc.querySelectorAll('p').forEach(p=>{if(!p.textContent.replace(/\u00a0/g,' ').trim()&&!p.querySelector('img,iframe,video')){p.classList.add('jk-empty-p')}});
const wrap=document.createElement('div');wrap.className='jk-inst-wrap';uc.before(wrap);
const hs=[...uc.querySelectorAll(':scope > h2, :scope > h3, :scope > h4')].filter(h=>h.textContent.trim().length>2);
if(hs.length>=4){const nav=document.createElement('aside');nav.className='jk-toc';nav.innerHTML='<span class="jk-toc-k">Nesta página</span>'+hs.map((h,i)=>{h.id=h.id||'jk-s'+i;return '<a href="#'+h.id+'">'+h.textContent.trim().replace(/^\d+[.)]\s*/,'')+'</a>'}).join('');wrap.appendChild(nav);wrap.classList.add('has-toc');
 nav.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;e.preventDefault();const t=document.getElementById(a.getAttribute('href').slice(1));window.scrollTo({top:t.getBoundingClientRect().top+scrollY-170,behavior:'smooth'})});
 const io=new IntersectionObserver(es=>es.forEach(en=>{if(en.isIntersecting){nav.querySelectorAll('a').forEach(a=>a.classList.toggle('on',a.getAttribute('href')==='#'+en.target.id))}}),{rootMargin:'-30% 0px -60% 0px'});hs.forEach(h=>io.observe(h))}
wrap.appendChild(uc);
const about=[...document.querySelectorAll('footer.js-footer a[href]')].find(x=>/sobre|quem somos|nossa hist|a marca/i.test(x.textContent));
if(about&&new URL(about.href,location.href).pathname.replace(/\/+$/,'')===location.pathname.replace(/\/+$/,'')){document.body.classList.add('jk-about');const img=uc.querySelector('img');const foto=img?img.src:'https://i.ibb.co/LDQk9B88/IMG-4955-2.jpg';if(img)img.closest('p,div')!==uc&&img.closest('p,div')?img.closest('p,div').remove():img.remove();
 const f=document.createElement('figure');f.className='jk-about-ph';f.innerHTML='<span class="jk-sb-arch"><img src="'+foto+'" alt=""></span>';wrap.prepend(f)}
})();;(()=>{if(!document.body.classList.contains('template-contact')||document.body.classList.contains('jk-ct'))return;document.body.classList.add('jk-ct','jk-inst');
const ul=document.querySelector('.template-contact ul.list');if(!ul)return;const box=ul.parentElement;box.classList.add('jk-ct-info');ul.parentElement.parentElement.classList.add('jk-ct-grid');
const ic={wa:'<path d="M3.6 20.4l1.3-4.1A8.6 8.6 0 1 1 8 19.3z"/><path d="M9 8.3c.2-.4.5-.5.8-.5h.4c.2 0 .4.1.5.4l.7 1.6c.1.2 0 .5-.1.7l-.6.7c.7 1.4 1.8 2.5 3.2 3.2l.7-.6c.2-.2.5-.2.7-.1l1.6.7c.3.1.4.3.4.5v.4c0 .3-.1.6-.5.8-.9.6-2.1.6-3.3.1a9 9 0 0 1-4.6-4.6c-.5-1.2-.5-2.4.1-3.3z"/>',tel:'<path d="M7.2 3.5h2.4l1.3 4-1.8 1.3a10 10 0 0 0 6.1 6.1l1.3-1.8 4 1.3v2.4a2 2 0 0 1-2.2 2C10.6 18.4 5.6 13.4 5.2 5.7a2 2 0 0 1 2-2.2z"/>',mail:'<rect x="3.5" y="5.5" width="17" height="13" rx="1.5"/><path d="M4 6.5l8 6.5 8-6.5"/>',pin:'<path d="M12 21s-6.5-6.1-6.5-11a6.5 6.5 0 0 1 13 0c0 4.9-6.5 11-6.5 11z"/><circle cx="12" cy="10" r="2.3"/>'};
const fmt=n=>{let d=String(n).replace(/\D/g,'');if(d.startsWith('55')&&d.length>11)d=d.slice(2);return d.length===11?'('+d.slice(0,2)+') '+d.slice(2,7)+'-'+d.slice(7):d.length===10?'('+d.slice(0,2)+') '+d.slice(2,6)+'-'+d.slice(6):n};
let wa=null;ul.querySelectorAll('li').forEach(li=>{const a=li.querySelector('a');const href=a?a.getAttribute('href')||'':'';const k=/wa\.me|whatsapp/i.test(href)?'wa':/^tel:/i.test(href)?'tel':/^mailto:/i.test(href)?'mail':'pin';const lbl={wa:'WhatsApp',tel:'Telefone',mail:'E-mail',pin:'Endereço'}[k];
 let txt=li.textContent.trim().replace(/\s+/g,' ');if(k==='wa'){txt=fmt(txt);wa=a.href}if(k==='tel')txt=fmt(txt);
 li.classList.add('jk-ct-it');li.innerHTML=(a?'<a href="'+a.href+'"'+(k==='wa'?' target="_blank" rel="noopener"':'')+'>':'<div>')+'<span class="jk-ct-ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round">'+ic[k]+'</svg></span><span class="jk-ct-tx"><small>'+lbl+'</small><b>'+txt+'</b></span>'+(a?'</a>':'</div>')});
if(wa){const b=document.createElement('a');b.className='jk-ct-wa';b.href=wa;b.target='_blank';b.rel='noopener';b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round">'+ic.wa+'</svg><span>Chamar no WhatsApp</span>';ul.after(b)}
const f=document.querySelector('.js-winnie-pooh-form');if(f){f.parentElement.classList.add('jk-ct-form');if(!f.querySelector('.jk-ct-ft')){const h=document.createElement('p');h.className='jk-ct-ft';h.textContent='Ou deixe sua mensagem';f.prepend(h)}}
})();;(()=>{if(!/template-account/.test(document.body.className)||document.body.classList.contains('jk-acc'))return;document.body.classList.add('jk-acc','jk-inst');
document.querySelectorAll('body > .container > div, body > .container > section:not(.page-header)').forEach(d=>{if(d.querySelector('form')&&!d.querySelector('table'))d.classList.add('jk-acc-card')});
const k={'template-account-login':'Bem-vinda de volta','template-account-reset':'Vamos recuperar seu acesso','template-account-newpass':'Defina sua nova senha'};const key=Object.keys(k).find(x=>document.body.classList.contains(x));
const h1=document.querySelector('section.page-header h1');if(h1&&key&&!document.querySelector('.jk-acc-sub')){const p=document.createElement('p');p.className='jk-acc-sub';p.textContent=k[key];h1.closest('section').after(p)}
})();;(()=>{if(window.__jkSpv)return;window.__jkSpv=1;
const fix=()=>document.querySelectorAll('[class*="js-products-"][class*="-container"] .swiper-container, .js-swiper-related').forEach(el=>{const sw=el.swiper;if(!sw||sw.__jkBp)return;const o=sw.originalParams.breakpoints||{};const k=Object.keys(o).map(Number).filter(x=>x>=700).sort((a,b)=>a-b)[0];if(!k)return;const d=o[k],n=d.slidesPerView;if(typeof n!=='number'||n<=3)return;sw.__jkBp=1;
 const mk=v=>Object.assign({},d,{slidesPerView:v,slidesPerGroup:Math.min(d.slidesPerGroup||v,v)});const bp=Object.assign({},o);delete bp[k];bp[768]=mk(3);bp[992]=mk(Math.min(n,4));bp[1200]=mk(n);
 sw.params.breakpoints=bp;sw.originalParams.breakpoints=bp;sw.currentBreakpoint=null;try{sw.setBreakpoint();sw.update()}catch(e){}});
fix();setTimeout(fix,1500);})();
})};if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",run)}else{run()}})();
